### ISSUE TITLE
Write a method to walk somebody through setting up their data and trackers

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/apex-legends-api#23]

**Comment by CondensedTea** [comment]
Hi, can you explain in more detail what features should be adden for user's data and trackers?

**Comment by johnsturgeon** [comment]
## Background
In order to have data show up in the API a player needs to do a few things:
1. they need to have the legend they want tracked in the lobby
2. they need to have the trackers they want tracked (i.e. 'kills', 'damage', 'wins') loaded up in the legends three visible 'trackers' (in the banner).

Once they have that, we can call the history API and it will load that data in for that legend.

If the user wants *all* their legends data tracked, then need to load each one of their legends into the lobby, one at a time with three trackers enabled, and call the 'history' API.

Once it's loaded, the totals should reflect the totals in game.

## This task
I think it would be nice to run a script that asks the users what data they would like tracked, and walk them through loading each legend and loading the data.

I imagine it would be something like
What data do you want tracked (choose 3):
Kills [K], Damage [D], Wins [W], Games Played [G]
... analyzing legends ... (here we would check the legends and see what data / or legend is not being tracked)
Please load Bloodhound with trackers for 'Kills' 'Damage' 'Wins' (or whatever they chose)
Press 'return' when bloodhound has been loaded
... getting data from bloodhound ...
Bloodhound:
  - Kills: 281
  - Damage: 28444
  - Wins: 12
Please load Bagalore...
(etc...) for all the legends
Totals:
  - Kills: 542
  - Damage: 93052
  - Wins 31

That's about it.. hope that makes sense

**Comment by johnsturgeon** [comment]
This really will be core to the apex-legends-tracker project .  I'm closing and cloning this issue over here:
https://github.com/johnsturgeon/apex-legends-tracker/issues/10
