### ISSUE TITLE
add a method `player.refresh_data()` 

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/apex-legends-api#24]
so that the events on a player, and any other data can be refreshed

**Comment by CondensedTea** [comment]
Would be this feature possible, if it requires storing data? How can it be done only with API?

**Comment by johnsturgeon** [comment]
I had imagined that somebody might instantiate a player object, and use it for, perhaps, display purposes and need to re-fresh the data, and using the new `since=timestamp` (not yet implemented but coming soon) could just pull new events into the player object, instead of re-creating it from the API again each time
The problem here is that the Player class does not know about the API (which is intended) so it might be a method on the API and not the 'player'.

This would be more useful for a daemon or something that has a player object that lasts for a while.

**Comment by johnsturgeon** [comment]
This no longer makes sense since I'm moving much of this capability over to this repo: https://github.com/johnsturgeon/apex-legends-tracker
