### ISSUE TITLE
Aggregate 'special event' trackers with normal trackers

### ISSUE THREAD

**Issue by johnsturgeon** [johnsturgeon/apex-legends-api#25]
That way when you have one legend with `specialEvent_kills` = 7 and another legend with `kills` = 10, your total_kills should be 17

**Comment by CondensedTea** [comment]
Would be stat "Total kills" shown in global_info or somewhere else?

**Comment by johnsturgeon** [comment]
the API has a 'totals' section, but it's just an aggregation of the legends data, so I was thinking that I would keep the 'totals' (use the 'tracker' class) and add a 'total_kills'

so we would have `player.totals.special_event_kills` `player.totals.kills` (and now) `player.totals.total_kills`  or something like that

**Comment by johnsturgeon** [comment]
I'm moving this issue over to my other repository. apex-legends-tracker

The reason is that I'm going to add more of this kind of logic to a 'tracker' instead of the core API.  This repo really should just get the data from apexlegendsapi.com

Cloned to: https://github.com/johnsturgeon/apex-legends-tracker/issues/9
