### ISSUE TITLE
Change query arguments from f-strings to request params

### ISSUE THREAD

**Issue by CondensedTea** [johnsturgeon/apex-legends-api#34]
docs: https://requests.readthedocs.io/en/latest/api/#main-interface

my MVP for this idea is working: 

```
payload = {'uid': uid, 'platform': 'PC', 'auth': token, 'history': 1, 'action': 'get'}
s = requests.Session()
response = s.get('https://api.mozambiquehe.re/bridge', params=payload)
```

@johnsturgeon What do you think?

**Comment by johnsturgeon** [comment]
Yep, should definitely do this.

Feel free to take this issue if you'd like
